server:
  port: 8765

spring:
  application:
    name: api-gateway

  cloud:
    inetutils:
      preferred-networks: true

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false