server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: api-gateway

  cloud:
    inetutils:
      preferred-networks: true

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
