
spring:
  config:
    import: configserver:http://192.168.1.76:8888
#    import: configserver:http://${LOCAL_IP}:8888

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.76:8761/eureka
#      defaultZone: http://${LOCAL_IP}:${server.port:eureka-server}/eureka